package clasesdb;
// Generated 18/04/2020 03:22:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tornillo generated by hbm2java
 */
public class Tornillo  implements java.io.Serializable {


     private int idtornillo;
     private Fabricante fabricante;
     private String cabeza;
     private Integer cuello;
     private Integer diametro;
     private String tiporosca;
     private Short paso;
     private Integer longitud;
     private String codigo;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Tornillo() {
    }

	
    public Tornillo(int idtornillo, Fabricante fabricante) {
        this.idtornillo = idtornillo;
        this.fabricante = fabricante;
    }
    public Tornillo(int idtornillo, Fabricante fabricante, String cabeza, Integer cuello, Integer diametro, String tiporosca, Short paso, Integer longitud, String codigo, Set<Cliente> clientes) {
       this.idtornillo = idtornillo;
       this.fabricante = fabricante;
       this.cabeza = cabeza;
       this.cuello = cuello;
       this.diametro = diametro;
       this.tiporosca = tiporosca;
       this.paso = paso;
       this.longitud = longitud;
       this.codigo = codigo;
       this.clientes = clientes;
    }
   
    public int getIdtornillo() {
        return this.idtornillo;
    }
    
    public void setIdtornillo(int idtornillo) {
        this.idtornillo = idtornillo;
    }
    public Fabricante getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(Fabricante fabricante) {
        this.fabricante = fabricante;
    }
    public String getCabeza() {
        return this.cabeza;
    }
    
    public void setCabeza(String cabeza) {
        this.cabeza = cabeza;
    }
    public Integer getCuello() {
        return this.cuello;
    }
    
    public void setCuello(Integer cuello) {
        this.cuello = cuello;
    }
    public Integer getDiametro() {
        return this.diametro;
    }
    
    public void setDiametro(Integer diametro) {
        this.diametro = diametro;
    }
    public String getTiporosca() {
        return this.tiporosca;
    }
    
    public void setTiporosca(String tiporosca) {
        this.tiporosca = tiporosca;
    }
    public Short getPaso() {
        return this.paso;
    }
    
    public void setPaso(Short paso) {
        this.paso = paso;
    }
    public Integer getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Integer longitud) {
        this.longitud = longitud;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


