package modelos;
// Generated 23/01/2020 02:42:01 PM by Hibernate Tools 4.3.1

//entidad Personas, POJOS Personas

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private String nroDocumento;
     private String direccion;
     private String telefono;

    public Personas() {
    }

    public Personas(String nombres, String apellidos, String nroDocumento, String direccion, String telefono) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.nroDocumento = nroDocumento;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNroDocumento() {
        return this.nroDocumento;
    }
    
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


